export const API_ENDPOINT = process.env.REACT_APP_API_ENDPOINT;
export const REACT_APP_GITHUB_ENDPOINT = process.env.REACT_APP_GITHUB_ENDPOINT;
export const REACT_APP_GITHUB_ACCESS_KEY = process.env.REACT_APP_GITHUB_ACCESS_KEY;